### PR TITLE
Replace deprecated assignment_tag decorated with simple_tag

### PR DESCRIPTION
**Pull request by shacker**
Re: https://github.com/alsoicode/django-admin-sortable/issues/176

### CODE REVIEW

**Comment by alsoicode** [comment]
Have you run the sample project in the repo using this change? I'm running into a few issues with rendering some of the template tags using Django 2.

**Comment by shacker** [comment]
I have not - I just have a simple SortableStackedInline/NonSortableParentAdmin usage in my own project.

**Comment by mimi89999** [comment]
@alsoicode Django 2.0 got released December 2. I updated my project for it and django-admin-sortable works very well with that line changed.

**Comment by alsoicode** [comment]
@mimi89999 Are the unit tests passing? I'm getting massive failures in my custom admin class.

**Comment by mimi89999** [comment]
I didn't try yet...

**Comment by alsoicode** [comment]
@mimi89999 Good news - something must have been messed up with my previous virtual env. I created a new one, made a few simple tweaks to the unit tests and everything is working with Django 2. I'm going to close this PR and pull in other changes to the session cookies, but I should be able to get a release out in the next day or so. I'm going to push what I currently have to master, so you can install from that if you're in a hurry.

**Pull request closed without merging**
